name: Unit tests
on:
  pull_request: { }
  push: { branches: main }

jobs:
  test:
    name: Run python unittests
    runs-on: ubuntu-latest
    container:
      image: jeffquinnmsk/protein-variant-nomenclature-parser:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install package
        run: pip uninstall protein-variant-nomenclature-parser

      - name: Run tests
        run: make install && make test
